# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aDreamLeaf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aDreamLeaf

    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'Charts'
    pod "MonthYearPicker", '~> 4.0.2'
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
    pod 'RxAlamofire'
    
    post_install do |installer|
        installer.generated_projects.each do |project|
              project.targets.each do |target|
                  target.build_configurations.each do |config|
                      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                   end
              end
       end
    end
end
